from collections.abc import (
    AsyncIterator,
    ItemsView,
    Iterable,
    Iterator,
    KeysView,
    Mapping,
    Sequence,
    ValuesView,
)

class Client:
    def __init__(self, http_version: HTTPVersion | None = None) -> None: ...
    async def execute(self, request: Request) -> Response: ...

class Headers:
    def __init__(
        self, items: Mapping[str, str] | Iterable[tuple[str, str]] | None = None
    ) -> None: ...
    def __getitem__(self, key: str) -> str: ...
    def __setitem__(self, key: str, value: str) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def add(self, key: str, value: str) -> None: ...
    def clear(self) -> None: ...
    def getall(self, key: str) -> Sequence[str]: ...
    def items(self) -> ItemsView[str, str]: ...
    def keys(self) -> KeysView[str]: ...
    def values(self) -> ValuesView[str]: ...
    def __contains__(self, key: object) -> bool: ...

class Request:
    def __init__(
        self,
        method: str,
        url: str,
        headers: Headers | Mapping[str, str] | Iterable[tuple[str, str]] | None = None,
        content: bytes | AsyncIterator[bytes] | None = None,
    ) -> None: ...

class Response:
    status: int
    headers: Headers
    content: AsyncIterator[bytes]
    trailers: Headers | None

class HTTPVersion:
    HTTP1: HTTPVersion
    HTTP2: HTTPVersion
    HTTP3: HTTPVersion
